config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts, only: [ :index, :show, :update ]

  root to: 'posts#index'
  namespace :login do
    root to: 'posts#index'
    resources :posts
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/login/application_controller.rb
class Login::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/login/posts_controller.rb
class Login::PostsController < Login::ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.posts.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to [:login, @post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [:login, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to login_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
    @comments = @post.comments.all
  end

  def update
    @post = Post.find(params[:id])
    @comment = @post.comments.build(comment_params)
    if @comment.save
      redirect_to post_path(@post)
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DailyBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand.navbar-dark.bg-dark
      = link_to "Daily Blog", "/", id: "logo", class: "navbar-brand"
      %ul.navbar-nav.ml-auto
        %li.nav-item
          = link_to "Blog", posts_path, class: "nav-link"
        -if current_user
          %li.nav-item
            = link_to "My Posts", login_posts_path, class: "nav-link"
          %li.nav-item
            = link_to "Edit User", edit_user_registration_path, class: "nav-link"
          %li.nav-item
            = link_to "Sign-out", destroy_user_session_path, method: :delete, class: "nav-link"
        -else
          %li.nav-item
            = link_to "Sign-in", new_user_session_path, class: "nav-link"
    .container
      = yield

app/views/login/posts/_form.html.haml
=bootstrap_form_for [:login, post] do |f|
  = f.text_field :title
  = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/login/posts/edit.html.haml
%h1 Editing post

= render 'form', post: @post

= link_to 'Show', [:login, @post]
\|
= link_to 'Back', login_posts_path

app/views/login/posts/index.html.haml
%h1 Listing posts

%table.table.table-striped
  %thead
    %tr
      %th Title
      %th Content
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.content
        %td= link_to 'Show', [:login, post]
        %td= link_to 'Edit', edit_login_post_path(post)
        %td= link_to 'Destroy', [:login, post], method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Post', new_login_post_path

app/views/login/posts/new.html.haml
%h1 New post

= render 'form', post: @post

= link_to 'Back', login_posts_path

app/views/login/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Content:
  = @post.content

= link_to 'Edit', edit_login_post_path(@post)
\|
= link_to 'Back', login_posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table.table.table-striped
  %thead
    %tr
      %th Title
      %th Content
  %tbody
    - @posts.each do |post|
      %tr
        %td= link_to post.title, post_path(post)
        %td= post.content

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Content:
  = @post.content

  %p
    %b Comments:
    - @comments.each do |comment|
      =comment.content

  =form_for @comment, url: post_path([@post, @comment]), method: :patch do |f|
    =f.text_field :content
    =f.submit 'Comment'